<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gunakan</name>
   <tag></tag>
   <elementGuidId>9c62de79-efd9-441d-80e1-676de5d98945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div/div[2]/div[2]/div/div/div[2]/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5de659f2-02e6-4b90-a7c2-6dceb0a64df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>07842139-7d17-4ce2-b7b1-7a0d2010fb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn--brand voucher__button</value>
      <webElementGuid>32c8a811-79df-4ca6-a178-c4f9a74ff033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gunakan</value>
      <webElementGuid>3083b2df-263e-42fd-97d7-552cc0711f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[4]/div[1]/div[@class=&quot;vouchers&quot;]/div[2]/div[@class=&quot;voucher__list--blue&quot;]/div[@class=&quot;voucher__panel&quot;]/div[@class=&quot;voucher__footer&quot;]/div[1]/div[@class=&quot;flex justify-between items-end&quot;]/a[@class=&quot;btn--brand voucher__button&quot;]</value>
      <webElementGuid>56a5de17-a073-4686-a2d4-c61ea5cc8fa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div/div[2]/div[2]/div/div/div[2]/div/div[3]/a</value>
      <webElementGuid>7cd4221a-ad07-4570-87e7-c874447dd308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Gunakan')])[2]</value>
      <webElementGuid>59ba6fff-fd0b-409a-9bd5-10ee5f9c08a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berkah10'])[1]/following::a[1]</value>
      <webElementGuid>4a136779-3c58-4c07-9217-a322f63709f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Voucher'])[2]/following::a[1]</value>
      <webElementGuid>e66bfac9-35b6-459e-94bf-38b505a9e1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potongan Ongkir untuk All Produk s.d Rp5.000'])[1]/preceding::a[1]</value>
      <webElementGuid>c30abbc0-d9cd-4086-8445-e67bd7b7b7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat S&amp;K'])[3]/preceding::a[1]</value>
      <webElementGuid>fe881c46-8a91-46ca-bec9-0ba166d9bc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>bc00bdcb-e508-4e8d-b4f4-c40055fc9edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[3]/a</value>
      <webElementGuid>7d85f7f4-8d5b-465e-a4a9-f9895b84d4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Gunakan' or . = 'Gunakan')]</value>
      <webElementGuid>4c41346c-9e02-4160-9a2d-6062f9c9ce8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
