<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Potongan Ongkir</name>
   <tag></tag>
   <elementGuidId>ad5ac5ba-9e10-4637-9897-a3f5845fb1b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55bfdae0-d5c8-45d9-99e4-2f131d5bf743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterSection__tab</value>
      <webElementGuid>78459cf7-ace6-4605-8b13-78fb5e81944a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Potongan Ongkir</value>
      <webElementGuid>a738c7d3-44cb-48db-a84a-bb76510f8162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[4]/div[1]/div[1]/div[@class=&quot;filterSection__tabs&quot;]/div[@class=&quot;filterSection__tab&quot;]</value>
      <webElementGuid>69770c9c-ce85-41b1-ae02-4e9bc58eb540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div/div/div/div[4]</value>
      <webElementGuid>c99b45f7-4ed1-47e9-bbdc-b73e9a9bb1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashback'])[1]/following::div[1]</value>
      <webElementGuid>5bf7249f-30b7-4de9-9bdc-82b59b4544ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium'])[1]/following::div[3]</value>
      <webElementGuid>6faa2e5a-4230-4a47-86e4-342b08ec1eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potongan Belanja'])[1]/preceding::div[2]</value>
      <webElementGuid>a955da19-91ba-4d29-baa6-7701c53f13ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[4]</value>
      <webElementGuid>96597ee8-1de7-4e40-9931-c28e04099ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Potongan Ongkir' or . = 'Potongan Ongkir')]</value>
      <webElementGuid>f8087215-593b-452c-9c9c-e7a7a7edd62e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
