<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pilih Alamat Pengiriman_pickedAddressId</name>
   <tag></tag>
   <elementGuidId>44474c3f-ec94-4c93-b3ad-038acb5623f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pickedAddressId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pickedAddressId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4044c96-e561-4140-a7f2-d7c8af2f2e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickedAddressId</value>
      <webElementGuid>7183b26b-b914-4db9-9c8a-aad6432913c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>32910650-e44f-4fce-b3b2-5cd5a17462a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100001071882</value>
      <webElementGuid>aa29c55f-fb6c-460e-a7fb-00c26a10a5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;modalDrawer&quot;]/div[@class=&quot;modalDrawer__panel&quot;]/div[@class=&quot;modalDrawer__wrapper&quot;]/div[@class=&quot;modalDrawer__wrapper&quot;]/div[2]/div[@class=&quot;addressLists scroll-y&quot;]/label[@class=&quot;addressList&quot;]/div[@class=&quot;addressList__head&quot;]/input[1]</value>
      <webElementGuid>6b543018-28e5-4b9a-9e4b-ace7600bfe6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pickedAddressId']</value>
      <webElementGuid>a5ed91df-512b-41c1-b31f-e4f3426d05c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div/div[2]/div/div[2]/div/label/div/input</value>
      <webElementGuid>483113e5-53c6-427b-a377-7583f8d9342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>d0491db6-8f43-469b-b947-8325010b6066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pickedAddressId' and @type = 'radio']</value>
      <webElementGuid>c3f86e02-a562-4115-bdc1-7257123ab86f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
