<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>81d804be-edd0-4370-a219-b5337fa17017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.productView__action__button.btn--brand > i > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[3]/div[3]/div[25]/div/div[2]/a/i/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>008ab971-21a9-4787-b748-a2aebe4a592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;productView&quot;]/div[@class=&quot;productView__body&quot;]/div[@class=&quot;productView__actions&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;productView__action&quot;]/a[@class=&quot;productView__action__button btn--brand&quot;]/i[1]/span[1]</value>
      <webElementGuid>e983ae5f-b28e-4012-af1c-be2d663ca170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[3]/div[3]/div[25]/div/div[2]/a/i/span</value>
      <webElementGuid>1fe944ef-0e82-4f5d-b719-677315543b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/div[2]/a/i/span</value>
      <webElementGuid>80a5a110-976d-4feb-ac68-b4afb45dc976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
