<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Rp10.000</name>
   <tag></tag>
   <elementGuidId>5929f4da-2b36-4f18-b7f5-30b89c80ee53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[7]/div[2]/div/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f82ae04d-5b4e-4816-9c71-349e61acf0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Rp10.000
				</value>
      <webElementGuid>d2908b40-7b5d-4564-96e4-e64ca189a8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;infaq__wrapper&quot;]/div[@class=&quot;infaq__panel&quot;]/div[@class=&quot;infaq__donation&quot;]/button[4]</value>
      <webElementGuid>f5f7eedd-f726-47f7-8338-69cc44983c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[7]/div[2]/div/button[4]</value>
      <webElementGuid>c7669ec6-13ba-48d3-9713-3af809ee68a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp5.000'])[2]/following::button[1]</value>
      <webElementGuid>42a7c7d4-f5a5-4426-9e98-23cefb363bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp2.500'])[1]/following::button[2]</value>
      <webElementGuid>a7f90d5a-5506-4e7c-bb77-a44e8029e2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total poin yang akan didapatkan'])[1]/preceding::button[1]</value>
      <webElementGuid>0fd5ea4a-89bb-453e-80c9-3e358f228746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian Pesanan'])[1]/preceding::button[1]</value>
      <webElementGuid>c54bbdc9-48b8-49c3-a472-daf179e13fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp10.000']/parent::*</value>
      <webElementGuid>c471fc19-962a-466d-bc3d-0047f415f9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>78ebd573-3be0-4517-b5fa-83c6ceea2ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
					Rp10.000
				' or . = '
					Rp10.000
				')]</value>
      <webElementGuid>32d8c13e-62de-459a-bae4-08c2c1be3ec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
