<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lihat Promo Tersedia_donationOffering</name>
   <tag></tag>
   <elementGuidId>30b9a9f1-8402-4000-b571-1a6c2c1c2b69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#donationOffering</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='donationOffering']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d686657f-7b89-40dc-b7e9-a8fd2081342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>donationOffering</value>
      <webElementGuid>79cd003c-a56d-4281-816b-d33f8606df57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a111b449-e833-4f0a-b951-55c0a535d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;donationOffering&quot;)</value>
      <webElementGuid>3b95beea-20cf-4299-af98-da53d2edf20b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='donationOffering']</value>
      <webElementGuid>3381bbfb-cdfd-4d3b-aa7e-429f42774821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[7]/div/input</value>
      <webElementGuid>894afbfa-e4a1-455c-9269-877e23a2684c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1aa935e9-c469-4348-98b9-0f037fcfe3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'donationOffering' and @type = 'checkbox']</value>
      <webElementGuid>f9744f57-0f34-4361-84fb-48166f0333af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
